// src/data.ts

export interface Profile {
    id: number;
    name: string;
    employer: string;
    college: string;
    location: string;
    bio: string;
    skills: string[];
    experience: number;
    pay: number;
    minHoursWeek: number;
    languages: string[];
  }

export const profiles: Profile[] = [
  {
    id: 1,
    name: 'Alexander Hamilton',
    employer: 'Treasury Department',
    college: "King's College (Columbia University)",
    location: 'New York, NY',
    bio: 'Founding Father, economist, and political philosopher.',
    skills: ['Economics', 'Political Philosophy', 'Leadership'],
    experience: 15,
    pay: 200,
    minHoursWeek: 30,
    languages: ['English', 'French'],
  },
  {
    id: 2,
    name: 'Ada Lovelace',
    employer: 'Analytical Engine',
    college: 'Self-taught',
    location: 'London, England',
    bio: 'Mathematician and writer, known for work on early mechanical general-purpose computers.',
    skills: ['Mathematics', 'Computing', 'Programming'],
    experience: 8,
    pay: 180,
    minHoursWeek: 25,
    languages: ['English', 'French', 'Italian'],
  },
  {
    id: 3,
    name: 'Marie Curie',
    employer: 'University of Paris',
    college: 'University of Paris',
    location: 'Paris, France',
    bio: 'Pioneer in the field of radioactivity, first woman to win a Nobel Prize.',
    skills: ['Physics', 'Chemistry', 'Radioactivity', 'Research'],
    experience: 20,
    pay: 220,
    minHoursWeek: 35,
    languages: ['Polish', 'French', 'English'],
  },
  {
    id: 4,
    name: 'Haruki Murakami',
    employer: 'Waseda University',
    college: 'Waseda University',
    location: 'Tokyo, Japan',
    bio: 'Renowned novelist and short story writer.',
    skills: ['Writing', 'Literature', 'Creative Writing', 'Storytelling'],
    experience: 30,
    pay: 150,
    minHoursWeek: 20,
    languages: ['Japanese', 'English'],
  },
  {
    id: 5,
    name: 'Sundar Pichai',
    employer: 'Google',
    college: 'Indian Institute of Technology Kharagpur',
    location: 'Mountain View, USA',
    bio: 'CEO of Alphabet Inc. and its subsidiary Google.',
    skills: ['Leadership', 'Technology Management', 'Software Engineering', 'Strategic Planning'],
    experience: 25,
    pay: 250,
    minHoursWeek: 40,
    languages: ['English', 'Tamil', 'Hindi'],
  },
  {
    id: 6,
    name: 'Angela Merkel',
    employer: 'German Federal Government',
    college: 'University of Leipzig',
    location: 'Berlin, Germany',
    bio: 'Former Chancellor of Germany and research scientist.',
    skills: ['Politics', 'Diplomacy', 'Leadership', 'Physics'],
    experience: 35,
    pay: 230,
    minHoursWeek: 38,
    languages: ['German', 'English', 'Russian'],
  },
  {
    id: 7,
    name: 'Yuna Kim',
    employer: 'Korea Skating Union',
    college: 'Korea University',
    location: 'Seoul, South Korea',
    bio: 'Former figure skater and Olympic champion.',
    skills: ['Figure Skating', 'Athletics', 'Choreography', 'Public Speaking'],
    experience: 18,
    pay: 190,
    minHoursWeek: 25,
    languages: ['Korean', 'English'],
  },
  {
    id: 8,
    name: 'Satya Nadella',
    employer: 'Microsoft',
    college: 'Manipal Institute of Technology',
    location: 'Redmond, USA',
    bio: 'CEO of Microsoft and author.',
    skills: ['Leadership', 'Cloud Computing', 'Business Strategy', 'Software Development'],
    experience: 28,
    pay: 245,
    minHoursWeek: 40,
    languages: ['English', 'Telugu', 'Hindi'],
  },
  {
    id: 9,
    name: 'Marie-Sophie Germain',
    employer: 'French Academy of Sciences',
    college: 'Self-taught',
    location: 'Paris, France',
    bio: 'Mathematician, physicist, and philosopher.',
    skills: ['Mathematics', 'Physics', 'Philosophy', 'Number Theory'],
    experience: 12,
    pay: 170,
    minHoursWeek: 30,
    languages: ['French', 'Latin'],
  },
  {
    id: 10,
    name: 'Hayao Miyazaki',
    employer: 'Studio Ghibli',
    college: 'Gakushuin University',
    location: 'Tokyo, Japan',
    bio: 'Film director, animator, and manga artist.',
    skills: ['Animation', 'Storytelling', 'Film Direction', 'Manga Art'],
    experience: 40,
    pay: 210,
    minHoursWeek: 35,
    languages: ['Japanese', 'English'],
  },
  {
    id: 11,
    name: 'Indra Nooyi',
    employer: 'PepsiCo',
    college: 'Indian Institute of Management Calcutta',
    location: 'Purchase, USA',
    bio: 'Former CEO of PepsiCo and business executive.',
    skills: ['Business Strategy', 'Leadership', 'Corporate Management', 'Finance'],
    experience: 30,
    pay: 240,
    minHoursWeek: 38,
    languages: ['English', 'Tamil', 'Hindi'],
  },
  {
    id: 12,
    name: 'Stephen Hawking',
    employer: 'University of Cambridge',
    college: 'University of Oxford',
    location: 'Cambridge, UK',
    bio: 'Theoretical physicist and cosmologist.',
    skills: ['Theoretical Physics', 'Cosmology', 'Scientific Writing', 'Public Speaking'],
    experience: 45,
    pay: 225,
    minHoursWeek: 25,
    languages: ['English'],
  },
  {
    id: 13,
    name: 'Park Geun-hye',
    employer: 'National Assembly of South Korea',
    college: 'Sogang University',
    location: 'Seoul, South Korea',
    bio: 'Former President of South Korea.',
    skills: ['Politics', 'Diplomacy', 'Public Policy', 'Leadership'],
    experience: 25,
    pay: 200,
    minHoursWeek: 40,
    languages: ['Korean', 'English', 'Chinese'],
  },
  {
    id: 14,
    name: 'Amartya Sen',
    employer: 'Harvard University',
    college: 'University of Calcutta',
    location: 'Cambridge, USA',
    bio: 'Economist and philosopher, recipient of the Nobel Memorial Prize in Economic Sciences.',
    skills: ['Economics', 'Philosophy', 'Social Choice Theory', 'Welfare Economics'],
    experience: 50,
    pay: 235,
    minHoursWeek: 30,
    languages: ['Bengali', 'English', 'Sanskrit'],
  },
  {
    id: 15,
    name: 'Angela Ahrendts',
    employer: 'Apple Inc.',
    college: 'Ball State University',
    location: 'Cupertino, USA',
    bio: 'Former Senior Vice President of Apple Retail.',
    skills: ['Retail Management', 'Business Strategy', 'Leadership', 'Brand Management'],
    experience: 22,
    pay: 220,
    minHoursWeek: 35,
    languages: ['English'],
  },
  {
    id: 16,
    name: 'Shinya Yamanaka',
    employer: 'Kyoto University',
    college: 'Kobe University',
    location: 'Kyoto, Japan',
    bio: 'Stem cell researcher and Nobel Prize laureate in Physiology or Medicine.',
    skills: ['Stem Cell Research', 'Molecular Biology', 'Genetics', 'Medical Research'],
    experience: 28,
    pay: 230,
    minHoursWeek: 38,
    languages: ['Japanese', 'English'],
  },
  {
    id: 17,
    name: 'Ursula von der Leyen',
    employer: 'European Commission',
    college: 'University of Göttingen',
    location: 'Brussels, Belgium',
    bio: 'President of the European Commission and former German defense minister.',
    skills: ['Politics', 'European Affairs', 'Leadership', 'Public Policy'],
    experience: 30,
    pay: 240,
    minHoursWeek: 40,
    languages: ['German', 'French', 'English'],
  },
  {
    id: 18,
    name: 'Kiran Mazumdar-Shaw',
    employer: 'Biocon',
    college: 'Bangalore University',
    location: 'Bangalore, India',
    bio: 'Entrepreneur and chairperson of Biocon Limited.',
    skills: ['Biotechnology', 'Entrepreneurship', 'Business Management', 'Research and Development'],
    experience: 35,
    pay: 210,
    minHoursWeek: 35,
    languages: ['English', 'Kannada', 'Hindi'],
  },
  {
    id: 19,
    name: 'Ban Ki-moon',
    employer: 'United Nations',
    college: 'Seoul National University',
    location: 'New York, USA',
    bio: 'Former Secretary-General of the United Nations.',
    skills: ['Diplomacy', 'International Relations', 'Leadership', 'Conflict Resolution'],
    experience: 40,
    pay: 245,
    minHoursWeek: 38,
    languages: ['Korean', 'English', 'French'],
  },
  {
    id: 20,
    name: 'Emmanuelle Charpentier',
    employer: 'Max Planck Unit for the Science of Pathogens',
    college: 'Pierre and Marie Curie University',
    location: 'Berlin, Germany',
    bio: 'Microbiologist and biochemist, co-inventor of CRISPR gene editing.',
    skills: ['Microbiology', 'Biochemistry', 'Gene Editing', 'CRISPR Technology'],
    experience: 25,
    pay: 220,
    minHoursWeek: 35,
    languages: ['French', 'English', 'German'],
  },
  {
    id: 21,
    name: 'Shigeru Miyamoto',
    employer: 'Nintendo',
    college: 'Kanazawa College of Art',
    location: 'Kyoto, Japan',
    bio: 'Video game designer and producer, creator of Mario and The Legend of Zelda.',
    skills: ['Game Design', 'Creative Direction', 'Character Design', 'Storytelling'],
    experience: 45,
    pay: 200,
    minHoursWeek: 30,
    languages: ['Japanese', 'English'],
  },
  {
    id: 22,
    name: 'Malala Yousafzai',
    employer: 'Malala Fund',
    college: 'University of Oxford',
    location: 'Birmingham, UK',
    bio: 'Activist for female education and the youngest Nobel Prize laureate.',
    skills: ['Activism', 'Public Speaking', 'Education Advocacy', 'Writing'],
    experience: 10,
    pay: 180,
    minHoursWeek: 25,
    languages: ['Pashto', 'Urdu', 'English'],
  },
  {
    id: 23,
    name: 'Demis Hassabis',
    employer: 'DeepMind',
    college: 'University of Cambridge',
    location: 'London, UK',
    bio: 'Artificial intelligence researcher and co-founder of DeepMind.',
    skills: ['Artificial Intelligence', 'Machine Learning', 'Neuroscience', 'Entrepreneurship'],
    experience: 20,
    pay: 240,
    minHoursWeek: 40,
    languages: ['English', 'Greek'],
  },
  {
    id: 24,
    name: 'Chanda Kochhar',
    employer: 'ICICI Bank',
    college: 'Jamnalal Bajaj Institute of Management Studies',
    location: 'Mumbai, India',
    bio: 'Former Managing Director and CEO of ICICI Bank.',
    skills: ['Banking', 'Finance', 'Leadership', 'Risk Management'],
    experience: 30,
    pay: 225,
    minHoursWeek: 38,
    languages: ['English', 'Hindi', 'Gujarati'],
  },
  {
    id: 25,
    name: 'Kazuo Ishiguro',
    employer: 'Self-employed',
    college: 'University of East Anglia',
    location: 'London, UK',
    bio: 'Nobel Prize-winning novelist and screenwriter.',
    skills: ['Writing', 'Literature', 'Screenwriting', 'Storytelling'],
    experience: 35,
    pay: 190,
    minHoursWeek: 25,
    languages: ['English', 'Japanese'],
  },
  {
    id: 26,
    name: 'Tu Youyou',
    employer: 'China Academy of Traditional Chinese Medicine',
    college: 'Peking University Health Science Center',
    location: 'Beijing, China',
    bio: 'Pharmaceutical chemist and Nobel laureate in Physiology or Medicine.',
    skills: ['Pharmaceutical Chemistry', 'Traditional Chinese Medicine', 'Drug Discovery', 'Medical Research'],
    experience: 50,
    pay: 230,
    minHoursWeek: 30,
    languages: ['Chinese', 'English'],
  },
  {
    id: 27,
    name: 'Elon Musk',
    employer: 'Tesla, SpaceX',
    college: 'University of Pennsylvania',
    location: 'Austin, USA',
    bio: 'Entrepreneur and business magnate, CEO of Tesla and SpaceX.',
    skills: ['Entrepreneurship', 'Innovation', 'Electric Vehicles', 'Space Technology'],
    experience: 25,
    pay: 250,
    minHoursWeek: 60,
    languages: ['English', 'Afrikaans'],
  },
  {
    id: 28,
    name: 'Esther Duflo',
    employer: 'Massachusetts Institute of Technology',
    college: 'École Normale Supérieure Paris-Saclay',
    location: 'Cambridge, USA',
    bio: 'Economist and Nobel laureate, co-founder of the Abdul Latif Jameel Poverty Action Lab.',
    skills: ['Economics', 'Development Economics', 'Poverty Alleviation', 'Research Methodology'],
    experience: 22,
    pay: 215,
    minHoursWeek: 35,
    languages: ['French', 'English'],
  },
];
